services:
  SmartCodeNet\GusApiBundle\Factory\GusFactory:
    arguments:
      - 'test'
      - 'true'

  SmartCodeNet\GusApiBundle\Factory\GusFactoryInterface: '@SmartCodeNet\GusApiBundle\Factory\GusFactory'
