services:
  SmartCodeNet\GusApiBundle\Factory\GusFactory:
    arguments:
      - '%user_key%'
      - '%user_test_key%'

  SmartCodeNet\GusApiBundle\Factory\GusFactoryInterface: '@SmartCodeNet\GusApiBundle\Factory\GusFactory'
