services:
  SmartCodeNet\GusApiBundle\Factory\GusFactory:
    public: true
    arguments:
      - ~
      - ~
  SmartCodeNet\GusApiBundle\Factory\GusFactoryInterface: '@SmartCodeNet\GusApiBundle\Factory\GusFactory'
