services:
  gusapibundle.gus_factory:
    class: SmartCodeNet\GusApiBundle\Factory\GusFactory
    public: true

  SmartCodeNet\GusApiBundle\Factory\GusFactoryInterface: '@SmartCodeNet\GusApiBundle\Factory\GusFactory'
